"""Initial Migration

Revision ID: 7a4991cd4b1c
Revises: 5b105591e1fb
Create Date: 2021-11-14 00:25:22.305825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a4991cd4b1c'
down_revision = '5b105591e1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'time_commented')
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'time_created')
    op.drop_column('posts', 'author')
    op.add_column('comments', sa.Column('time_commented', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author')
    op.drop_column('comments', 'time_created')
    # ### end Alembic commands ###
